# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    municipios:
        class: Test\InterviewBundle\Service\MunicipiosService
        arguments: ['@logger', '@doctrine.orm.entity_manager']

    check_provincia_is_available:
        class: Test\InterviewBundle\Service\CheckProvinciaIsAvailableService
        arguments: ['@logger', '@doctrine.orm.entity_manager']

    find_all_provincias_and_municipios_by_comunidad:
        class: Test\InterviewBundle\Service\FindAllProvinciasAndMunicipiosByComunidadService
        arguments: ['@logger', '@doctrine.orm.entity_manager']
